server:
  port: 2001
  servlet:
    context-path: /uaa
spring:
  application:
    name: uaa-service
  cloud:
    nacos:
      discovery:
        server-addr: 10.5.0.111:8848
        username: nacos
        password: nacos
        group: SPRING_CLOUD
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.5.0.111:3306/note_and_read?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
# 开启日志 方便调试
logging:
  level:
    org.springframework.web: trace
    org.springframework.security: trace
    org.springframework.security.oauth2: debug
mybatis:
  mapperLocations: classpath*:mapper/*.xml
  type-aliases-package: org.springboot.sample.entity
  config-location: classpath:config/mybatis-config.xml