server:
  port: 2002
spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: 10.5.0.111:8848
        username: nacos
        password: nacos
        group: SPRING_CLOUD